14:51:16 - ERR - post - (<BadRequest '400: Bad Request'>,)
14:51:35 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "host.docker.internal" (192.168.3.19), port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.3.19\xbb, usuario \xabdawau\xbb, base de datos \xabRedSocial\xbb, sin cifrado\n', 101, 102, 'invalid continuation byte'),)
14:51:35 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
14:52:16 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "host.docker.internal" (192.168.3.19), port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.3.19\xbb, usuario \xabdawau\xbb, base de datos \xabRedSocial\xbb, sin cifrado\n', 101, 102, 'invalid continuation byte'),)
14:52:16 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
14:52:36 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "host.docker.internal" (192.168.3.19), port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.3.19\xbb, usuario \xabdawau\xbb, base de datos \xabRedSocial\xbb, sin cifrado\n', 101, 102, 'invalid continuation byte'),)
14:52:36 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
14:53:02 - ERR - login - (TypeError('can only concatenate str (not "NoneType") to str'),)
15:26:17 - ERR - login - (KeyError('u_id'),)
15:29:24 - ERR - login - (TypeError("'NoneType' object is not subscriptable"),)
15:32:20 - ERR - login - (TypeError("'NoneType' object is not subscriptable"),)
